version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
      PGDATA: /database
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse
    command: web
    links: [db, vault]
    depends_on: [db, vault]
    ports: ["8080:8080"]
    volumes: 
    - "./keys/web:/concourse-keys"
    - "./certs:/certs"
    environment:
      CONCOURSE_EXTERNAL_URL: https://concourse.DNS.com
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_VAULT_URL: https://vault:8200
      CONCOURSE_VAULT_PATH_PREFIX: /concourse
      CONCOURSE_VAULT_AUTH_BACKEND: cert
      CONCOURSE_VAULT_CA_CERT: /certs/rootca.cert
      CONCOURSE_VAULT_CLIENT_CERT: /certs/concourse/concourse.cert
      CONCOURSE_VAULT_CLIENT_KEY: /certs/concourse/concourse.key
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  vault:
    image: "vault"
    cap_add:
      - IPC_LOCK
    ports: ["8200:8200"]
    volumes: 
      - ./certs/vault:/vault/config
    command: vault server -config /vault/config/vault.hcl 
